// my_sys_hbm_fp_0.v

// Generated using ACDS version 22.4 94

`timescale 1 ps / 1 ps
module my_sys_hbm_fp_0 (
		output wire       ch0_u0_wmc_intr,   //   ch0_u0_wmc_intr.conduit
		output wire       ch0_u1_wmc_intr,   //   ch0_u1_wmc_intr.conduit
		input  wire       hbm_reset_in,      //      hbm_reset_in.reset
		output wire       hbm_cattrip,       //           cattrip.hbm_cattrip
		input  wire       hbm_cattrip_i,     //         cattrip_i.conduit
		output wire [2:0] hbm_temp,          //              temp.hbm_temp
		input  wire [2:0] hbm_temp_i,        //            temp_i.conduit
		output wire       local_cal_success, // local_cal_success.local_cal_success
		output wire       local_cal_fail,    //    local_cal_fail.local_cal_fail
		input  wire       uibpll_refclk,     //     uibpll_refclk.clk
		output wire       wmcrst_n           //          wmcrst_n.reset_n
	);

	my_sys_hbm_fp_0_hbm_fp_110_edhc4xy hbm_fp_0 (
		.ch0_u0_wmc_intr   (ch0_u0_wmc_intr),   //  output,  width = 1,   ch0_u0_wmc_intr.conduit
		.ch0_u1_wmc_intr   (ch0_u1_wmc_intr),   //  output,  width = 1,   ch0_u1_wmc_intr.conduit
		.hbm_reset_in      (hbm_reset_in),      //   input,  width = 1,      hbm_reset_in.reset
		.hbm_cattrip       (hbm_cattrip),       //  output,  width = 1,           cattrip.hbm_cattrip
		.hbm_cattrip_i     (hbm_cattrip_i),     //   input,  width = 1,         cattrip_i.conduit
		.hbm_temp          (hbm_temp),          //  output,  width = 3,              temp.hbm_temp
		.hbm_temp_i        (hbm_temp_i),        //   input,  width = 3,            temp_i.conduit
		.local_cal_success (local_cal_success), //  output,  width = 1, local_cal_success.local_cal_success
		.local_cal_fail    (local_cal_fail),    //  output,  width = 1,    local_cal_fail.local_cal_fail
		.uibpll_refclk     (uibpll_refclk),     //   input,  width = 1,     uibpll_refclk.clk
		.wmcrst_n          (wmcrst_n)           //  output,  width = 1,          wmcrst_n.reset_n
	);

endmodule
