// uib_clkref.v

// Generated using ACDS version 22.3 104

`timescale 1 ps / 1 ps
module uib_clkref (
		input  wire  in_clk,  //  in_clk.clk
		output wire  out_clk  // out_clk.clk
	);

	assign out_clk = in_clk;

endmodule
