// axi_reset.v

// Generated using ACDS version 22.4 94

`timescale 1 ps / 1 ps
module axi_reset (
		input  wire  in_reset,  //  in_reset.reset
		output wire  out_reset  // out_reset.reset
	);

	assign out_reset = in_reset;

endmodule
